export const ALL_MOVIE_REQUEST = "ALL_MOVIE_REQUEST";
export const ALL_MOVIE_SUCCESS = "ALL_MOVIE_SUCCESS";
export const ALL_MOVIE_FAIL = "ALL_MOVIE_FAIL";

export const FAVOURITE_MOVIE_REQUEST = "FAVOURITE_MOVIE_REQUEST";
export const FAVOURITE_MOVIE_SUCCESS = "FAVOURITE_MOVIE_SUCCESS";
export const FAVOURITE_MOVIE_FAIL = "FAVOURITE_MOVIE_FAIL";

export const SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_FAIL = "SEARCH_MOVIE_FAIL";

export const ADD_OR_REMOVE_FAVOURITE_REQUEST =
  "ADD_OR_REMOVE_FAVOURITE_REQUEST";
export const ADD_OR_REMOVE_FAVOURITE_SUCCESS =
  "ADD_OR_REMOVE_FAVOURITE_SUCCESS";
export const ADD_OR_REMOVE_FAVOURITE_FAIL = "ADD_OR_REMOVE_FAVOURITE_FAIL";

export const NEW_MOVIE_REQUEST = "NEW_MOVIE_REQUEST";
export const NEW_MOVIE_SUCCESS = "NEW_MOVIE_SUCCESS";
export const NEW_MOVIE_RESET = "NEW_MOVIE_RESET";
export const NEW_MOVIE_FAIL = "NEW_MOVIE_FAIL";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_RESET = "UPDATE_MOVIE_RESET";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL";

export const COUNT_REQUEST = "COUNT_REQUEST";
export const COUNT_REQUEST_FAIL = "COUNT_REQUEST_FAIL";
export const ALL_COUNT_TOTAL = "ALL_COUNT_TOTAL";
export const ADD_MOVIE_COUNT = "ADD_MOVIE_COUNT";
export const ADD_CATEGORY_COUNT = "ADD_CATEGORY_COUNT";
export const ADD_USER_COUNT = "ADD_USER_COUNT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
